Final-DAMDA/FE_DAMDA

src/components/common/BlueButton/index.tsx
src/components/common/BlueButton/style.ts
src/pages/sale/index.tsx
src/styles/Sale.styled.ts

#11 옷 판매 대행 페이지 80% 제작완료 및 파란 버튼 컴포넌트 제작

---

src/utils/auth.ts

fix: redirect URI 수정

---

src/apis/auth.ts
src/components/common/Header/HeaderLayout.tsx
src/components/common/Header/index.tsx
src/components/common/Layout/index.tsx
src/hook/useAuth.ts
src/pages/login/index.tsx
src/store/auth.ts
src/types/auth.ts

feat: 유저상태관리

---

src/components/common/Header/HeaderLayout.tsx
src/components/common/Header/style.ts
src/pages/manager/completed/index.tsx
src/styles/Completed.styled.ts

매니저 서비스 완료 폼 90퍼 제작

---

package-lock.json
package.json
src/apis/auth.ts
src/apis/code.ts
src/components/common/Header/HeaderLayout.tsx
src/components/review/ImageSlide/style.ts
src/hook/useAuth.ts
src/pages/completed-user/[id].tsx
src/pages/completed-user/index.tsx
src/styles/CompletedUser.styled.ts
src/styles/Review.styled.ts
src/utils/auth.ts
yarn.lock

고객 서비스 완료 페이지 추가

---

src/components/common/Header/HeaderLayout.tsx

fix: 헤더 레이아웃 숨김옵션에 서비스완료페이지 추가

---

src/pages/login/index.tsx
src/store/routeHistory.ts

feat: 로그인 후 기존페이지 복귀

---

src/apis/code.ts
src/components/completedUser/CompletedUserLayout.tsx
src/pages/completed-user/index.tsx

feat: 사용자 할인코드 받아오기 api 연결

---

src/apis/form.ts
src/components/usersurvey/components/Radio.tsx
src/components/usersurvey/index.tsx
src/components/usersurvey/step/FirstStep.tsx
src/components/usersurvey/step/SecStep.tsx
src/store/userSurvey.ts
src/styles/survey.styled.ts
src/types/api/formTypes.ts
src/utils/index.ts

[유저 서비스 신청 페이지] price 노출 컴포넌트 및 제출 로직

---

src/apis/review.ts
src/components/common/Header/HeaderLayout.tsx
src/components/common/Layout/index.tsx
src/components/common/ModalContainer/style.ts
src/components/completedUser/CompletedUserLayout.tsx
src/components/review/BestReview/index.tsx
src/components/review/ImageSlide/index.tsx
src/components/review/ImageSlide/style.ts
src/components/review/ReviewItem.tsx
src/components/review/ReviewLayout.tsx
src/components/review/ReviewModal/index.tsx
src/pages/completed-user/index.tsx
src/pages/review/index.tsx
src/styles/CompletedUser.styled.ts
src/types/review.ts

feat: review데이터 받아오기 staticProps 연결

---

src/components/common/FAB/index.tsx
src/components/common/FAB/style.ts
src/components/common/Header/Menu/style.ts
src/components/common/Header/style.ts
src/components/common/Layout/index.tsx
src/components/common/Layout/style.ts
src/components/common/SideFloating/index.tsx
src/components/common/SideFloating/style.ts
src/components/main/MainLayOut.tsx

태블릿 반응형 구현

---

src/components/common/FAB/style.ts
src/components/common/Header/Menu/style.ts
src/components/common/Layout/index.tsx
src/components/common/Layout/style.ts
src/components/common/ModalContainer/style.ts
src/components/review/ImageSlide/style.ts
src/constants/dummyRevies.ts
src/pages/review/index.tsx
src/store/routeHistory.ts

pc대응 반응형 적용 및 리뷰 렌더링이슈 해결

---

src/pages/review/index.tsx

fix: 리뷰 호출 함수 수정

---

src/components/common/FAB/index.tsx
src/components/common/SideFloating/index.tsx
src/components/usersurvey/step/SecStep.tsx
src/constants/mainButtonText.ts
src/pages/manager/accept/[id].tsx

[메인페이지 수정]

---

src/components/customerCenter/customerCenterLayout/index.tsx

고객센터 페이지 1:1 상담 신청 링크 설정

---

src/components/usersurvey/components/Input.tsx
src/components/usersurvey/index.tsx
src/pages/usersurvey/index.tsx
src/styles/survey.styled.ts

[유저 서비스신청 페이지] HOTFIX: store를 null로 설정하여 에러 수정

---

src/components/common/Carousel/index.tsx
src/components/common/Carousel/style.ts
src/components/main/UserReview.tsx
src/components/review/BestReview/index.tsx
src/components/usersurvey/components/Input.tsx
src/components/usersurvey/index.tsx
src/components/usersurvey/step/FirstStep.tsx
src/components/usersurvey/step/SecStep.tsx
src/store/userSurvey.ts
src/utils/isValidAnswer.ts

[유저 서비스 신청 페이지] valid 과정 추가

---

src/components/main/UserReview.tsx
src/styles/Main.styled.ts

fix: 레이아웃 깨지는 부분 수정

---

src/apis/auth.ts
src/components/common/Header/index.tsx
src/hook/useAuth.ts
src/pages/login/index.tsx
src/pages/review/index.tsx
src/store/auth.ts
src/utils/auth.ts

카카오 로그인 앱 변경

---

src/components/usersurvey/components/Input.tsx
src/components/usersurvey/index.tsx

[유저 서비스 신청] 이름에 대한 예외처리

---

src/hook/useAuth.ts
src/types/auth.ts

fix: 로그인 실패처리

---

src/apis/manager.ts
src/components/manager/accept/AcceptLayout.tsx
src/pages/manager/accept/[id].tsx

[매니저 매칭 수락 페이지]

---

src/styles/Main.styled.ts

fix: 메인의 이미지가 제대로 보이지 않았던 문제 해결

---

src/components/managerForm/LocationSelectionForm/index.tsx
src/components/managerForm/index.tsx
src/components/managerForm/introductionForm/index.tsx

매니저 지원 폼 이름 인풋 문제 해결
